name: Test logic and interface

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Setup
      run: npm run setup
    - name: Run Logic Tests
      run: npm run test:ci
    - name: Run Interface Tests
      run: npm run build --ci && npx start-server-and-test start 3000 'olsk-spec-ui --ci'
